import Head from 'next/head'
import Game from '../components/game'

export default function Home() {



  return (
    <div>
      <Head>
        <title>Effrat Katz | Memory Game</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
       <Game />
      </main>

      <footer>
      </footer>
    </div>
  )
}
